[tool.poetry]
name = "zvonokin"
version = "0.1.0"
description = ""
authors = ["care1e55"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
pydantic-settings = "^2.2.1"
typer = "0.12.3"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.0"
mypy = "^1.0.0"
black = "24.4.2"
